### PR TITLE
Made solve.py Python3-compatible

### PR DESCRIPTION
**Pull request by aliskin**
- replaced urllib2 with urllib
- added brackets for print

### CODE REVIEW

**Comment by pedrobalage** [comment]
@ramon-astudillo, can you approve this pull request? 

I verified and it is everything ok. 

We also need to modify the guide from:

python ./solve.py day1
to 
python solve.py linear_classifiers

I will make the pull request for this change.

Pedro

**Comment by dcferreira** [comment]
I didn't test it, but I'm pretty sure it's missing the ``from __future__ import print_function`` for py2 compatibility.

**Comment by luispedro** [comment]
@dcferreira Using `print` with a single argument and parentheses is actually Python 2/3 compatible. Python 2 doesn't need them, but it is not incorrect to have extra parentheses.

**Comment by dcferreira** [comment]
Ah, good to know. Disregard my previous comment then :)

**Comment by ramon-astudillo** [comment]
> We also need to modify the guide from:
> 
> python ./solve.py day1
> to
> python solve.py linear_classifiers
> 
> I will make the pull request for this change.

Thanks @pedrobalage

**Pull request merged**
